import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState, useEffect } from "react";
import styles from "./page.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [link, setLink] = useState();

  useEffect(() => {
    const fetchLink = async () => {
      const response = await fetch("http://localhost:3030/buy-loaf");
      const data = await response.json();
      setLink(data.data);
    };

    fetchLink();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div>
            <Image
              className={styles.logo}
              src="/loaf.png"
              alt="loaf Logo"
              width={180}
              height={180}
              priority
            />
          </div>
          <div>
            <a
              href="https://t.me/$FkuCNp286FXQAQAAuCZqxn709_4"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2>
                Buy <span>-&gt;</span>
              </h2>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div>
            <Image
              className={styles.logo}
              src="/toast-icon.svg"
              alt="toast icon"
              width={180}
              height={180}
              priority
            />
          </div>
          {link}
          <div>
            {link && (
              <a
                href={link}
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
              >
                <h2>
                  Buy <span>-&gt;</span>
                </h2>
              </a>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
